name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Angular build
      - name: Build Angular app
        run: npm run build --if-present

      # Step 5: Run tests
      - name: Run tests
        run: npm test

      # Step 6: Upload build artifacts (optional)
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/